# Generated by Django 3.0.2 on 2020-02-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailer',
            name='sended',
            field=models.BooleanField(default=False),
        ),
    ]
